import "../styles/globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import BG from "/img/IndigoDesigns_BabyGirl_pp+(7)1.jpg";
import Image from "next/image";
import Menu from "@/components/Menu/Menu";

export const metadata = {
  title: "Diora Kids",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Image className="bg" priority={true} src={BG} alt="" />

        <main className="main">
          <Header />
          <Menu />
          <div className="content">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
